### ISSUE TITLE
todo: update readme and stabilize project

### ISSUE THREAD

**Issue by mckaygerhard** [MoonLightDE/mlde.l.cppmicroservices#2]
when fork the project was a featured library, today the project are staled and must be update the info as minimal to provide other that want to continue.. 

 - [x] update README with related info: b7896c8db5063947f6fe9317b9aa29b6543cf4b0
 - [x] separate lib issues from ain MLDE project f30d68bc9cac89c1ffc76264045e87caf3ee75db
 - [x] migrate current issues 
 - [x] fix build infraestructure to minimal to package f30d68bc9cac89c1ffc76264045e87caf3ee75db
 - [x] make the repository a fork and staled
